---
roles:
  - name: geerlingguy.security
    version: 2.4.0
  - name: geerlingguy.firewall
    version: 2.6.0
  - name: geerlingguy.git
    version: 3.0.1
  - name: geerlingguy.pip
    version: 3.1.0
  - name: geerlingguy.supervisor
    version: 3.1.1
  - name: geerlingguy.docker
    version: 7.4.3
  - name: fedejaure.rpi_lcd
    version: 0.2.0

collections:
  - name: community.docker
    version: 4.1.0
  - name: community.general
    version: 10.1.0
